### ISSUE TITLE
Improve description of "nam" field

### ISSUE THREAD

**Issue by benlaurie** [ehn-dcc-development/eu-dcc-schema#132]
https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/a603410d760fefc9073931c8c807759d9714c136/DCC.schema.json#L44 does not match https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.0/DCC.Core.Types.schema.json.

**Comment by dslmeinte** [comment]
What's the mismatch?

**Comment by dslmeinte** [comment]
@benlaurie As with the other issue you raised: thanks for being so precise, and sorry about the short answer.

Taking the files from the latest release (1.3.1), then the `nam` property defined [here](https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.1/DCC.schema.json#L46) is a reference to the `person_name` definition [here](https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.1/DCC.Core.Types.schema.json#L17). I don't understand just yet how that leads to a mismatch, but I'm happy to learn, as the devil is always in the details - certainly with interoperability.

**Comment by benlaurie** [comment]
Ah. I foolishly thought that the description was meaningful. Clearly person_name is not "Person name: Surname(s), forename(s) - in that order", it is structured data that does not even have to include forenames.

So instead the bug is "person_name/description is incorrect".

**Comment by benlaurie** [comment]
Also, if 1.3.1 is the current release, why is 1.3.0 the default?

**Comment by dslmeinte** [comment]
> So instead the bug is "person_name/description is incorrect".

Ah, I now see your point! What would you like as a better description? (For starting an iteration.) 

> Also, if 1.3.1 is the current release, why is 1.3.0 the default?

1.3.1 should indeed be the default: I'll get back to you on that.

**Comment by benlaurie** [comment]
Well, it should probably say its a structure defining a person's name. Also, since some of the fields refer to a "standardised name" it would be helpful to know what standard that is.

**Comment by Xiphoseer** [comment]
> Well, it should probably say its a structure defining a person's name. Also, since some of the fields refer to a "standardised name" it would be helpful to know what standard that is.

According to <https://ec.europa.eu/health/sites/health/files/ehealth/docs/covid-certificate_json_specification_en.pdf> the standard is

> Surname(s) of the holder transliterated using the same convention as the one used in the holder’s machine readable travel documents (such as the rules defined in ICAO Doc 9303 Part 3).

**Comment by dslmeinte** [comment]
@benlaurie @Xiphoseer @ryanbnl What do you think of the following for `person_name`'s `description`?:

> The person's name consisting at least of a separate standardised surname, or a standardised forename, or both - with standardisation done according to the rules defined in ICAO Doc 9303 Part 3
